### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by nlambert**
Specifies that withFeatures requires query to be provided via props
- [x] Add example in examples folder
- [x] Document props for withFeatures()

### CODE REVIEW

**Comment by kennylavender** [comment]
@nlambert no one was assigned to review, just checking if your still working on this or is it ready to be reviewed?

**Comment by nlambert** [comment]
Yes ready to be reviewed

**Comment by kennylavender** [comment]
@nlambert I think linking to external examples is fine, but I think it should be in addition to an example in this projects [examples folder](https://github.com/paralleldrive/react-feature-toggles/tree/master/examples). Just in case those external examples change, get moved or deleted. What do you think? 

Also I think we should add props section to the api section for [withFeatures](https://github.com/paralleldrive/react-feature-toggles/blob/master/README.md#withfeatures)

**Comment by kennylavender** [comment]
Also, I don't think the `Setup` section of the docs makes sense anymore based on the changes we made.

We would need to add a `withQuery` hoc or that passes the query to `withFeatures` or something else that passes the query to `withFeatures`. Which might bring up the question, for __non__ nextjs apps that are client side only do we provide a `withQuery` hoc for convenience?

```javascript
const pageHOC = compose(
  withRedux,
  withQuery,
  withFeatures({ initialFeatures }),
  hoc1,
  hoc2
);
```

**Comment by kennylavender** [comment]
nvm. Just realized that `react-redux-wrapper` passes through query for you ;)

**Comment by nlambert** [comment]
Added a todo list (see top) that I will look into. Did I understand correctly? @kennylavender

**Comment by kennylavender** [comment]
Yup looks good!

**Comment by nlambert** [comment]
- added examples
- added documentation
- added `propTypes` to withFeatures component

**Comment by kennylavender** [comment]
@ericelliott we should be good to publish the breaking change if your good with these doc changes for now!

**Comment by kennylavender** [comment]
This should wrap up #72

**Pull request merged**
