### PR TITLE
Autocurry configure feature

### PR DESCRIPTION
**Pull request by ericelliott**

### CODE REVIEW

**Comment by ericelliott** [comment]
Published as `@paralleldrive/react-feature-toggles@2.1.0`

**Comment by kennylavender** [comment]
@ericelliott I removed auto currying from all functions for a few reasons

- default arguments break auto curry
  - tests won't catch this breakage unless the tests use unary curry format
- the extra documentation of explaining auto curry in each function was just clutter and got in the way.
- the manually curried format is no extra characters and I have become fond of this simplicity :)

If you still prefer auto curry though we can add back auto curry to the other functions.

**Comment by ericelliott** [comment]
> * default arguments break auto curry

This function doesn't use them, and you can specify the number of parameters you're expecting with `lodash/fp/curry` so it will even work with defaults.

> * the extra documentation of explaining auto curry in each function was just clutter and got in the way.

I think the extra API convenience makes up for it. Explaining why you have to write `foo(a)(b)` instead of `foo(a, b)` is more confusing, IMO. Particularly for people unfamiliar with curried functions in JavaScript.

I definitely prefer autocurry for this one. Let's make the decision on a case-by-case basis. `configureFeature` is used *a lot*, and it's nice if it behaves as users expect it to behave.

**Comment by kennylavender** [comment]
Ok, sounds good.

**Pull request merged**
